
models:
  - name: stg_pol
    description: "Cleaned staging model for policy data"
    columns:
      - name: policy_id
        tests:
          - not_null
          - unique
      - name: premium_amount
        tests:
          - not_null

  - name: fact_premium
    description: "Premium calculation model"
    columns:
      - name: premium_with_gst
        tests:
          - not_null
